project:
  type: book

book:
  title: "Plataformas en 2D"
  author: "Luis E. Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - gameDesign.qmd
    - config.qmd
    - jugador.qmd
    - enemigo.qmd
    - danio.qmd
    - coleccionables.qmd
    - puntaje.qmd
    - iu.qmd
    - retoques.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml



