project:
  type: book

book:
  title: "Desarrollo de Videojuegos"
  author: "Luis E. Mendoza"
  date: "02/22/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Introducción"
      chapters:
        - conceptosclave.qmd
        - primer2D.qmd
        - primer3D.qmd
    - part: "Plataformas"
      chapters:
        - 2D.qmd
        - 3D.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt



