# RPG por turnos

## Diseño del juego

### Descripción general

Un RPG basado en turnos se divide en una serie de eventos en los que cada caracter decide qué hacer en un combate. Gana el primero en derrotar a su oponente. En primer instancia, el juego cuenta con dos personajes: el jugador a la izquierda y la IA a la derecha. Cada turno le pertenece a uno de esos personajes. Si es el turno del jugador, este decidirá qué acción realizar. Si es el turno del caracter de la IA, la acción será determinada automáticamente con base en funciones preestablecidas.

### Elementos del caracter

Cada personaje en el juego tendrá su respectivo "sprite" que flotará arriba y abajo y se coloreará de rojo cuando reciba daño. Además tendrá una barra de vida que disminuirá si el caracter ha sido atacado o aumentará si este se cura; dichos cambios se podrán notar visual y numéricamente.

### Movimientos de combate

Son recursos que representan varias acciones que un personaje puede ejecutar durante su turno, pudiendo ser ataques o curaciones. Esas acciones contarán con los siguientes elementos:

- **Nombre**: Un nombre definido para el movimiento.
- **Descripción**: Lo que la movimiento realiza.
- **Daño/Cura**: La cantidad de daño/salud que la acción causa/repone.
- **Ponderación**: El valor que influye el proceso de toma de decisiones de la IA, causando que ciertas acciones tengan mayor probabilidad de ser elegidas.

### Turno del jugador

Un panel aparecerá al fondo de la pantalla, permitiendo al jugador elegir cuál movimiento realizará. Estará dividido en dos secciones:

- **Izquierda**: Botones representando los diferentes movimientos asignados al jugador.
- **Derecha**: Nombre y descripción del movimiento.

Cuando el jugador elija un movimiento, causará daño a la IA o se curará a sí mismo, entonces dejando el turno para la IA.
Player’s Turn

### Turno de la IA

Una función determinará la acción a realizar. Esta decision estará basada en los siguientes factores:

- **Vida de la IA**: La cantidad actual de salud del caracter de la IA.
- **Vida del jugador**: La cantidad actual de salud del personaje del jugador.
- **Peso aleatorio del movimiento**: Un valor que influye sobre lo atractivo de un movimiento dado.

La IA ajustará la ponderación de los movimientos basada en su propia salud. Por ejemplo, si es baja, le será más atractivo curarse. La IA escogerá un movimiento aleatorio basada en esas ponderaciones.

## Configuración del proyecto

Primero crearemos las carpetas que le darán estructura básica a nuestro proyecto: `actions`, `assets`, `scenes` y `scripts`. Luego importaremos los assets, los cuales se encuentran en la plataforma.

Enseguida crearemos una escena cuyo nodo raíz será un `Node2D` al cual llamaremos `Main`. Guardamos la escena pero como `battle.tscn`.

Agregamos un nodo `TextureRect` que renombramos como `Background`. Luego, a `Main` le agregamos un `Camera2D`. Nos devolvemos a `Background`, cuya *Texture* será ocupada con la carga de `backgroundCastles.png`. Lo reubicamos y redimensionamos de manera que quede  cubierto el viewport de la cámara recién agregada. Luego, en su propiedad *Stretch Mode* le cambiamos por `Tile` para que al moverlo o cambiarlo de tamaño se repita a lo largo del viewport. Por último, para asegurarnos de que siempre quede al fondo, nos vamos a su propiedad *CanvasItem -> Ordering -> Z Index* y le damos un valor negativo (puede ser simplemente `-1`).

## Los personajes

Este juego contará con dos caracteres: el que controlará el jugador y el de la IA. Ambos combatirán por turnos hasta que la vida de uno de los dos llegue a cero. Crearemos y programaremos primero al jugador, para enseguida estar trabajando con los movimientos.

### Creando los personajes

Ambos caracteres derivan de la misma escena, lo único que los diferenciará será el lado para donde estén volteando. Eso lo controlaremos mediante código.

Primeramente creamos al jugador mediante un nodo `Node2D` que será hijo de `Main`. Lo llamaremos `Character`. Debido a que el personaje no se estará moviendo ni interactuará con físicas, no es necesario agregar una forma de colisión.

Añadamos a `Character` un nodo `Sprite2D` cuya textura será nuestro asset del dragón (`Dragon.png`). Vamos a aplicarle un *Offset Y* de `-70` para que así su pivote quede entre sus pies. Le añadimos a `Character` un `AudioStreamPlayer` y le adjuntamos su respectivo `character.gd`.

### Programando los personajes

Como ya se pudo haber notado, ambos caracteres serán básicamente el mismo, con la salvedad de que uno es controlado por la IA y otro por nosotros. Debido a ello, podemos programar ambos en su estructura básica.

#### Creando la clase

Abriremos `character.gd` y crearemos nuestra primera **clase**, la cual nos permitirá llamar al script desde cualquier parte de nuestro programa. Agregamos entonces lo siguiente al script:

```gdscript
# Creamos nuestra clase Character
class_name Character
```

#### Creando señales

Siguiente, crearemos las señales que nuestro script emitirá. Serán solo dos: una cuando se reciba daño y otra cuando se cure. Ambas enviarán la salud actual del caracter como parámetro.

```gdscript
# Señal de daño
signal OnTakeDamage (health : int)
# Señal de curación
signal OnHeal (health : int)
```

#### Declarando variables

Ahora declararemos las variables necesarias. Después de las señales pondremos lo siguiente:

```gdscript
# Variable lógica que indica si el caracter es el jugador
@export var is_player : bool
# Muestra la salud actual del caracter
@export var cur_health : int
# Guarda la vida máxima del caracter
@export var max_health : int
# Muestra la escala hacia la cual va el caracter. Muestra el turno del jugador
var target_scale : float = 1.0
# Referencia al AudioStreamPlayer
@onready var audio : AudioStreamPlayer = $AudioStreamPlayer
# Precarga el audio de daño
var take_damage_sfx : AudioStream = preload("res://assets/Audio/take_damage.wav")
# Precarga el audio de sanación
var heal_sfx : AudioStream = preload("res://assets/Audio/heal.wav")
```

#### Creando funciones adicionales

Necesitaremos varias funciones que nos permitan realizar las acciones de nuestro juego. Debido a ello, las armamos, aunque aún no las terminemos de desarrollar. Eso lo haremos conforme las vayamos necesitando.

Si no creamos el script con una plantilla vacía, ya tenemos `_process(delta)`. En caso contrario, la añadiremos. Agreguemos pues las siguientes estructuras:

```gdscript
# Llamada cuando comience el turno del caracter
func begin_turn ():
	# Mayor a 1: turno del caracter
	target_scale = 1.1

# Llamada cuando finalice el turno
func end_turn ():
	# Menor a 1: fin del turno
	target_scale = 0.9

# Recibir daño
func take_damage (amount : int):
	pass

# Sanación
func heal (amount : int):
	pass

# Realizar un movimiento
func cast_combat_action (action, opponent):
	pass

# Reproducri el sonido correspondiente
func _play_audio (stream : AudioStream):
	pass
```

## El *GameManager*

Programaremos el script que administrará el juego en sí, es decir, gestionará los turnos y el estado del juego en el sistema de combate.

### Programando el *GameManager*

Seleccionaremos `Main` y le adjuntaremos su respectivo script, al cual llamaremos `game_manager.gd`.

#### Variables

Declararemos las siguientes variables:

```gdscript
# Definen al caracter actual
@export var player_character : Character
@export var ia_character : Character
# Almacena cuál caracter es el actual
var current_character : Character
# Verifica si el juego ha terminado
var game_over : bool = false
```

#### Gestión de los turnos

La función principal será `next_turn()`. Esta será llamada en cualquier momento que termine el turno de un caracter. Gestionará el cambio de turnos entre jugador e IA.

```gdscript
# Gestión del cambio de turnos
func next_turn():
	# Si el juego ha terminado:
	if game_over:
		# Retorna
		return

	# Si el caracter no es nulo:
	if current_character != null:
		# Termina el turno para ese caracter
		current_character.end_turn()

	# Si el caracter actual es la IA o es nulo:
	if current_character == ia_character or current_character == null:
		# Cede el turno al jugador
		current_character = player_character
	# Si no:
	else:
		# Cede el turno a la IA
		current_character = ia_character

	# Comienza el turno para el caracter actual
	current_character.begin_turn()
```

#### Manejo de los movimientos de la IA

Necesitamos conducir los movimientos del jugador y la IA durante sus turnos, habilitando la IU del jugador, agregando un tiempo de espera para la IA (será artificial, la IA realmente no lo necesita) y ejecutar los movimientos. Agregamos el siguiente código al final de `next_turn()`

```gdscript
	# Si es turno del jugador:
	if current_character.is_player:
		# Habilita la IU
		pass # Por mientras
	# Si no
	else:
		# Deshabilita la IU si aún está activa
		# Genera un tiempo de espera entre 0.5 y 1.5 segundos
		var wait_time = randf_range(0.5, 1.5)
		await get_tree().create_timer(wait_time).timeout
		# Ejecuta el movimiento
		await get_tree().create_timer(0.5).timeout
		# La función se manda a llamar a sí misma
		next_turn()
```

#### Manejo de los movimientos del jugador

Esta función entrará cuando el jugador ejecute algún movimiento mediante su IU.

```gdscript
# Gestión de los movimientos del jugador
func player_cast_combat_action(action : CombatAction):
	# Si el caracter no es el jugador:
	if player_character != current_character:
		# Retorna
		return
	# El jugador ejecuta un movimiento contra la IA
	player_character.cast_combat_action(action, ia_character)
	# Deshabilita la IU y espera medio segundo
	await get_tree().create_timer(0.5).timeout
	# Llama al siguiente turno
	next_turn()
```

#### Selección de movimiento por la IA

Dejaremos solo la estructura de esta función, ya que requiere más elementos. Dejemos en que será la que gestione la respuesta de la IA ante los movimientos del jugador.

```gdscript
# Gestión de las decisiones de la IA
func ia_decide_combat_action() -> CombatAction:
	return null
```

Godot nos marcará que no reconoce el tipo de dato `CombatAction`. Sin problema, lo declararemos más delante.

## Los turnos

### Configurando

Conectemos los componentes que ya hemos desarrollado y gestionemos los turnos de cada caracter. Guardemos el `Character` como una escena nueva (`character.tscn`), pero aún dentro de `battle.tscn` lo seleccionamos y lo reubicamos en *Position X* igual a `-230`. Lo duplicamos y movemos su copia a *Position X* en `230`. Renombramos los nodos como `PlayerCharacter` e `IACharacter`. Habilitamos la propiedad *Is Player* para el `PlayerCharacter`.

Luego, con `Main` seleccionado, en el inspector asignamos `PlayerCharacter` en *Player Character* e `IACharacter` en *IA Character*. Guardamos.

### Implementando las mecánicas

Dentro de la función `_ready()` del `game_manager.gd` (si no la tenemos la creamos) mandamos llamar a `next_turn()`

```gdscript
func _ready():
	next_turn()
```

## Los movimientos

Esta es la sección más compleja del juego. Es aquí donde usaremos recursos para crear y gestionar los movimientos que pueden realizar ambos caracteres.

### Los recursos

En Godot usamos recursos cuando queremos contar con datos que pueden ser almacenados en los archivos del juego y que deseamos utilizar cuando sean necesarios. Los recursos pueden ser escenas, audios, scripts, imágenes e incluso crear uno nuevo. En el juego de Plataformas 2D usamos un recurso: el tilemap. Para este juego, crearemos un tipo llamado `CombatAction`.

Para crear un movimiento, primero crearemos un script nuevo. Vayamos al sistema de archivos de Godot y en la carpeta de `scripts` damos clic derecho para crear un nuevo script. Le llamaremos `combat_action.gd`. Podemos tranquilamente borrar todo el código predefinido y agregamos esto al principio:

```gdscript
# Definimos la clase
class_name CombatAction

# Cambiamos el tipo de herencia a Recurso
extends Resource

# Declaramos variables
# Nombre del movimiento
@export var display_name : String
# Descripción
@export var description : String
# Daño a melée
@export var melee_damage : int = 0
# Cantidad de sanación
@export var heal_amount : int = 0
# Ponderación
@export var base_weight : int = 100
```

### Creando un recurso de movimiento

Toca crear nuestro primer movimiento o `CombatAction`. Damos clic derecho en la carpeta `actions` y luego en *Crear nuevo -> Recurso*. En el buscador localizamos `CombatAction`, lo elegimos y le damos en crear. Le nombraremos `slash.tres`. Entonces damos doble clic al elemento en el sistema de archivos y nos debe mostrar sus propiedades en el inspector. Las editamos con los siguientes valores:

- *Display Name*: `Slash`
- *Description*: `Deal 8 damage` (o en español)
- *Melee Damage*: `8`
- *Heal Amount*: `0`

Dejamos la última propiedad en `100`.

Crearemos al menos otros dos movimientos: una curación (`heal.tres`) y un golpe pesado (`heavy_hit.tres`). Repitamos los mismos pasos pero con los siguientes valores:

Para la curación,

- *Display Name*: `Heal`
- *Description*: `Heal 10 health points` (o en español)
- *Melee Damage*: `0`
- *Heal Amount*: `10`

Para el golpe pesado, que sí es más deseable que la IA trate de hacerlo,

- *Display Name*: `Heavy Hit`
- *Description*: `Deal 15 damage` (o en español)
- *Melee Damage*: `15`
- *Heal Amount*: `0`
- *Base Weight*: `150`

### Integrando los movimientos a los caracteres

Abrimos `character.gd` y agregamos una variable que guardará el arreglo de movimientos:

```gdscript
# Arreglo de movimientos
@export var combat_actions : Array[CombatAction]
```

Ya podemos asignar los movimientos a los personajes. Seleccionamos el `PlayerCharacter` y en el inspector damos clic en su propiedad *Combat Actions*. Le damos un tamaño de `3` y mediante la carga rápida o arrastrando desde el sistema de archivos le asignamos nuestras tres acciones (`heal.tres`, `heavy_hit.tres` y `slash.tres`).

### Actualizando el código

En `character.gd` actualizamos la función `cast_combat_action()`:

```gdscript
func cast_combat_action(action: CombatAction, opponent: Character):
	pass
```

Y en `game_manager.gd` agregamos al final de `next_turn()` pero antes del segundo `await`

```gdscript
        # Permitimos a la IA decidir qué hacer
		var action_to_cast = ia_decide_combat_action()
		# Ejecuta el movimiento
		ia_character.cast_combat_action(action_to_cast, player_character)
```

## Menú del jugador

En esta sección configuraremos el menú de acciones o movimientos que tendrá disponibles el jugador. También le agregaremos una pequeña ayuda contextual cuando el jugador coloque su cursor en el movimiento.

### Configurando el panel de acciones

Comenzaremos agregando un `CanvasLayer` a `Maín`, que nos permitirá dibujar en pantalla los diferentes elementos de la interfaz gráfica de manera consistente, sin importar la posición de la cámara.

Enseguida, al `CanvasLayer` le vamos a añadir un nodo `Panel` como hijo. Le renombramos como `CombatActionsUI`. En la propiedad *Size X* le pondremos `450` y en *Size Y* `155`. Enseguida anclamos dicho panel en el *Centro Inferior*. Probemos la escena. `Panel` debe estar centrado y en la parte inferior. Vamos a subirlo un poco para dejar un pequeño margen por debajo.

Dividiremos el `Panel` en dos secciones: la izquierda donde colocaremos los botones de movimiento y la derecha donde incluiremos una breve descripción de cada uno. Veamos la primera.

Con `CombatActionsUI` seleccionado, agregaremos un nodo `VBoxContainer` y le llamaremos `ButtonsContainer`. Este es una especie de rejilla que contendrá los elementos que le coloquemos dentro. Lo redimensionamos de manera que cubra la mitad del panel. Acto seguido, agregamos un `Button` al contenedor. Ponemos cualquier nombre de movimiento ("Slash" está bien) y luego lo duplicamos hasta conseguir los cuatro botones básicos de nuestra interfaz. Podemos mover un poco el contenedor o incluso redimensionarlo para que se vea mejor dentro de nuestro panel. Una vez que el contenedor esté bien dimensionado, borraremos los últimos tres botones, solo los usamos como referencia.

Ahora configuraremos la otra mitad del `CombatActionsUI`. Lo seleccionamos y añadimos un nodo `RichTextLabel`. Este nodo nos permite mostrar texto en formato enriquecido (BBCode) y será donde le mostraremos al jugador la descripción del movimiento que tenga seleccionado con el cursor. Le cambiamos el nombre a este último nodo para llamarle simplemente `Description` y lo redimensionamos de manera que cubra la mayor parte de la mitad derecha del `CombatActionsUI`. Bueno, ahora escribimos el nombre del movimiento de esta manera: `[b]Slash[/b]` y su breve descripción, la cual la escribimos de la manera usual.

Posiblemente el texto se vea borroso. Si ese es el caso, nos vamos a la configuración del proyecto, apartado *General -> GUI -> Tema* y activamos el *Campo de distancia con firma multicanal de Fuente predeterminado*. Después damos clic en *Guardar y reiniciar*. Godot se cerrará y volverá a abrir.

### Programando el panel de acciones

Seleccionamos el único botón que tenemos (o el primero en su defecto) y le adjuntamos su script. Ahí crearemos una clase llamada `CombatActionButton`, crearemos una variable de tipo `CombatAction` y armamos una función que nos permita cambiar de acción o movimiento y su texto en consecuencia.

El código que nos permite hacer lo anterior se muestra enseguida:

```gdscript
extends Button

# clase nueva
class_name CombatActionButton

# variable de tipo CombatAction
var combat_action : CombatAction

# función que actualiza el texto en el botón
func set_combat_action(ca : CombatAction):
	combat_action = ca
	text = ca.display_name
```

Procedemos a duplicar tres veces nuestro botón para ya completar los cuatro, con la salvedad de que al último le cambiaremos el nombre para que quede como `PassTurnButton`, su campo de texto lo cambiamos a "Terminar turno" y además, sustraeremos el script que heredó del botón original.

Adjuntamos un script al `CombatActionsUI` y lo guardamos con su respectivo nombre. Dentro del script agregaremos algunas variables: la referencia al `ButtonsContainer`, el arreglo que incluye las diferentes acciones de combate, la descripción de cada movimiento y la ruta del *GameManager*.

```gdscript
@onready var buttons_container = $ButtonsContainer
var ca_buttons : Array[CombatActionButton]

@onready var description_text : RichTextLabel = $Description
@onready var game_manager = $"../.."
```

Ahora configuraremos la función `_ready()`, en la cual incluiremos un ciclo que iterará buscando todos los botones:

```gdscript
func _ready():
	# buscamos los botones
	for child in buttons_container.get_children():
		# Si el botón no es una acción de combate
		if child is not CombatActionButton:
			# sigue de largo
			continue
		# agrega el botón al arreglo
		ca_buttons.append(child)
```

Toca programar las señales. Deseamos que la descripción aparezca cuando colocamos el cursor en el botón y desaparezca al abandonarlo. Además, cuando se presione el botón, debe ejecutar la acción correspondiente. Agreguemos entonces dichas funciones, de momento como "dummies" para comprobar su funcionamiento. Escribamos dentro del `for` de `_ready()` lo siguiente:

```gdscript
# Conectamos la señal de botón presionado al botón
		child.pressed.connect(_button_pressed.bind(child))
		# Conectamos la señal de cursor entrando al botón
		child.mouse_entered.connect(_button_entered.bind(child))
		# Conectamos la señal de cursor saliendo al botón
		child.mouse_exited.connect(_button_exited.bind(child))
```

Ahora, crearemos la funciones que mandamos llamar en cada evento:

```gdscript
# Función de presionar el botón
func _button_pressed(button : CombatActionButton):
	print("Presionao")

# Función de cursor entrando al botón
func _button_entered(button : CombatActionButton):
	print("Señalao")

func _button_exited(button : CombatActionButton):
	print("Saliendo")
```

Tal como dijimos antes, no tenemos aún la funcionalidad final, pero si probamos la escena, debería indicar en la consola el mensaje pertinente tras realizar cada acción.

Viendo que todo funcione bien, cambiemos el `print()` de las funciones por la auténtica línea:

```gdscript
# Función de presionar el botón
func _button_pressed(button : CombatActionButton):
	# Llamamos al game manager pidiendo el movimiento asociado
	game_manager.player_cast_combat_action(button.combat_action)
```

```gdscript
# Función de cursor entrando al botón
func _button_entered(button : CombatActionButton):
	# Actualizamos la descripción del movimiento
	var ca = button.combat_action
	description_text.text = "[b]" + ca.display_name + "[/b]\n" + ca.description
```

```gdscript
func _button_exited(button : CombatActionButton):
	# Reiniciamos el texto de la descripción
	description_text.text = ""
```

Finalmente, conectaremos el botón de ceder el turno. Seleccionamos el botón (`PassTurnButton`) y mediante el panel de *Señales* conectamos su señal `pressed()` al `CombatActionsUI`. En la función que aparece sustituimos el `pass` con

```gdscript
func _on_pass_turn_button_pressed():
	# Cede el turno
    game_manager.next_turn()
```

Para mostrar correctamente los movimientos al jugador usaremos una función que tome un arreglo que los incluya como argumento y los asigne a los botones. Si tenemos más botones que acciones disponibles, que los deshabilite.

```gdscript
func set_combat_actions(actions: Array[CombatAction]):
	# Recorre los botones
	for i in len(ca_buttons):
		# Si son más botones que acciones:
		if i >= len(actions):
			# deshabilitarlos
			ca_buttons[i].visible = false
			# Continuar
			continue

		# Los botones son visibles
		ca_buttons[i].visible = true
		# Se asigna la acción al botón
		ca_buttons[i].set_combat_action(actions[i])
```

No corramos el juego. Es seguro que nos dará un error ya que aún no definimos todo.

Debemos irnos al `game_manager.gd` y declarar una nueva variable que haga referencia a la interfaz gráfica para controlar la visibilidad de las acciones.

```gdscript
# Referencia al panel de movimientos
@onready var player_ui = $CanvasLayer/CombatActionsUI
```

Ahora modifiquemos la función `next_turn()` para mostrar los movimientos solo cuando sea turno del jugador:

```gdscript
func next_turn():
	# Si el juego ha terminado:
	if game_over:
		# Retorna
		return

	# Si el caracter no es nulo:
	if current_character != null:
		# Termina el turno para ese caracter
		current_character.end_turn()

	# Si el caracter actual es la IA o es nulo:
	if current_character == ia_character or current_character == null:
		# Cede el turno al jugador
		current_character = player_character
	# Si no:
	else:
		# Cede el turno a la IA
		current_character = ia_character
	# Comienza el turno para el caracter actual
	current_character.begin_turn()

	# Si es turno del jugador:
	if current_character.is_player:
		# Habilita la IU
		player_ui.visible = true
		player_ui.set_combat_actions(player_character.combat_actions)
	# Si no
	else:
		# Deshabilita la IU si aún está activa
		player_ui.visible = false
		# Genera un tiempo de espera entre 0.5 y 1.5 segundos
		var wait_time = randf_range(0.5, 1.5)
		await get_tree().create_timer(wait_time).timeout
		# Permitimos a la IA decidir qué hacer
		var action_to_cast = ia_decide_combat_action()
		# Ejecuta el movimiento
		ia_character.cast_combat_action(action_to_cast, player_character)
		await get_tree().create_timer(0.5).timeout
		# La función se manda a llamar a sí misma
		next_turn()
```

También queremos ocultar la IU cuando el jugador ya haya realizado algún movimiento. Agregamos esta línea a la función `player_cast_combat_action()` justo antes del `await`

```gdscript
player_ui.visible = false
```

Probemos el juego. Todo debería ir bien.

## La barra de vida

Este elemento es informativo y permite al jugador reajustar su combate y tomar decisiones. Así que procedamos a desarrollarla.

### Configurando la barra de vida

Abramos `character.tscn` y seleccionemos `Character`. Le añadiremos un nodo `ProgressBar` que llamaremos HealthBar`. Deshabilitemos su propiedad *Show Percentage*, mientras que en la sección *Range* cambiamos solo su propiedad *Value* a un `45` de manera temporal. Luego, en su propiedad *Transform -> Size X* la cambiamos a `212`. Dejamos su *Size Y* igual. Lo vamos a reposicionar de manera que quede debajo del sprite del personaje, con cierto margen superior. Luego, en el apartado *Theme Overrides* buscaremos las propiedades *Styles -> Background* y *Styles ->  Fill*. Los desplegamos y creamos un nuevo *StyleBoxFlat* y cambiamos su *BGColor* a uno que nos parezca adecuado. Por ejemplo, un gris para el primero y un rojo para el segundo.

Ahora, deseamos mostrar el valor correspondiente en la barra (no como porcentaje). Para ello, con `HealthBar` seleccionado añadimos un nodo `Label` que renombramos como `HealthText`. Luego le aplicamos un anclaje "Completo". Enseguida escribimos en su campo de texto "50 / 100" como referencia y cambiamos su *Horizontal Alignment* y *Vertical Alignment* a `Center`. Por último, en su *Label Settings* creamos un nuevo recurso `LabelSettings` y lo abrimos. Cambiamos el tamaño de fuente a `22` y le aumentamos la opacidad a su sombra con un *Offset* de `2` en ambas coordenadas.

### Programando la barra de vida

Vamos a adjuntar un script al `HealthBar` y le llamaremos `character_health_bar.gd`. Declararemos una variable, tal como se muestra:

```gdscript
# Referencia al texto de la barra
@onready var health_text : Label = $HealthText
```

Luego procedemos a programar las funciones que actualizarán el valor de la barra y su texto:

```gdscript
func _ready():
	# Referenciamos al nodo padre (Character)
	var chara = get_parent()
	# Definimos su vida máxima con el valor máximo permitido
	max_value = chara.max_health
	# Actualizamos su vida actual
	_update_value(chara.cur_health)
	# Conectamos la señal de daño a la función que actualiza
	# la vida actual
	chara.OnTakeDamage.connect(_update_value)
	# También conectamos la señal de curación
	chara.OnHeal.connect(_update_value)

# Función que actualizará los valores actuales de la vida
func _update_value (health : int):
	# Manda el valor de vida actual
	value = health
	# Manda el valor a la etiqueta
	health_text.text = str(health) + " / " + str(int(max_value))
```

Nos vamos a la escena de batalla y ahí seleccionamos el `PlayerCharacter` y modificamos las propiedades *Cur Health* y *Max Health* a `100`, por ejemplo. Hacemos lo mismo con el `IACharacter`.

## Las mecánicas de combate

Ahora habilitaremos a los caracteres para que puedan "golpear" y "curarse", todo eso mientras el juego responde de manera adecuada.

### ¿Estamos atacando o curándonos?

Abrimos `character.gd` y nos dirigimos a la función `cast_combat_action()`. En ella agregamos el código siguiente:

```gdscript
func cast_combat_action(action: CombatAction, opponent: Character):
	# Si no hay acción:
	if action == null:
		# retorna
	# Si la acción tiene daño a melee:
	if action.melee_damage > 0:
		# el oponente recibirá el daño de la acción
		opponent.take_damage(action.melee_damage)
	# Si la acción cura:
	if action.heal_amount > 0:
		# el caracter se cura lo que indique la acción
		heal(action.heal_amount)
```

### Recibiendo daño

Ahora programamos la función que le restará a la vida del personaje la cantidad de daño indicada en la acción realizada y emitirá la señal para que actualicemos la vida del caracter.

```gdscript
# Recibir daño
func take_damage (amount : int):
	# Restamos el daño
	cur_health -= amount
	# Emitimos la señal
	OnTakeDamage.emit(cur_health)
	# Reproducimos el sonido de daño
	_play_audio(take_damage_sfx)
```

### Curando

Toca implementar la función de curación. Esta agregará la cantidad indicada por la acción pero se asegurará de que no supere la vida máxima. La función nos quedará así:

```gdscript
# Sanación
func heal (amount : int):
	# Suma la cantidad de salud a la vida
	cur_health += amount
	# Limita la curación a la vida máxima
	cur_health = clamp(cur_health, 0, max_health)
	# Emite la señal de curación
	OnHeal.emit(cur_health)
	# Reproduce el sonido adecuado
	_play_audio(heal_sfx)
```

### Sonando

Por último, para que se reproduzcan los sonidos correspondientes, debemos completar la función `_play_audio()`:

```gdscript
# Reproducri el sonido correspondiente
func _play_audio (stream : AudioStream):
	audio.stream = stream
	audio.play()
```

Ahora sí, probemos el juego. Al menos el personaje del jugador puede curarse y dañar a la IA, a la vez que se reproducen los sonidos adecuados. Por cierto, si no podemos ver los cambios tras una curación, modifiquemos la salud actual del caracter en el inspector y probemos de nuevo. La curación no debe superar la vida máxima.

## La IA del enemigo

Comenzaremos configurando las funciones que permitan a la IA el tomar decisiones que le permitan derrotar al jugador. Contrario a este último, la IA necesita un proceso lógico para decidir sus movimientos. Implementaremos un sistema de aleatoriedad ponderada para llevar a cabo dicho proceso.

### Entendiendo la aleatoriedad ponderada

Esta nos permitirá influir en la preferencia de la IA por ejecutar ciertas acciones de combate. Cada acción tiene una ponderación base que determinará su oportunidad de ser elegida y realizada. Mientras mayor sea este peso base, más preferencia tendrá el movimiento por ser realizado. Sin embargo, modificaremos esos pesos con base en la salud tanto de la IA como del jugador para tomar decisiones más estratégicas.

### Configurando la función de decisiones

Primero vamos a delinear los pasos que debemos realizar para implementar esta función. Debemos establecer las variables necesarias primero, luego calcularemos los porcentajes de vida del jugador y la IA, para utilizarlos y modificar las ponderaciones en consecuencia para así elegir el movimiento aleatorio basado en esas ponderaciones finales.

#### Variables necesarias

Vayamos al `game_manager.gd` y modifiquemos la función `ia_decide_combat_action` para asegurarnos que sea turno de la IA:

```gdscript
func ia_decide_combat_action() -> CombatAction:
	# Si la IA no es el jugador actual:
	if ia_character != current_character:
		# no regresa nada
		return null

	return null
```

Luego, creamos las variables justo antes del último `return null`:

```gdscript
# Alias para las variables
	var ia = ia_character
	var player = player_character
	var actions = ia.combat_actions

	# Variables para rastrear las ponderaciones
	var weights: Array[int] = []
	var total_weight = 0
```

#### Calculando porcentajes de vida

Agregamos justo debajo de la última variable que declaramos en el bloque anterior las siguientes líneas que nos permiten calcular ambos porcentajes:

```gdscript
	# Calculamos el porcentaje de salud de la IA
	var ia_health_perc = float(ia.cur_health) / float(ia.max_health)
	# Calculamos el porcentaje del jugador
	var player_health_perc = float(player.cur_health) / float(player.max_health)
```

#### Determinando las ponderaciones

Iteraremos a través de cada movimiento en el arreglo de acciones de combate de la IA y modificaremos las ponderaciones con base en ciertas condiciones. Luego sumaremos la ponderación final al total de pesos. Escribimos enseguida, en el mismo bloque de función:

```gdscript
	# Iteramos a través de las acciones
	for action in actions:
		# Variable que toma el peso base de la acción
		var weight : int = action.base_weight
		# Si la salud actual del jugador es menor o igual que el daño
		# del movimiento:
		if player.cur_health <= action.melee_damage:
			# multiplica el peso base por 3
			weight *= 3

		# Si es movimiento de curación:
		if action.heal_amount > 0:
			# aumenta su peso mientras menos vida tenga la IA
			weight *= 1 + (1 - ia_health_perc)

		# Añadimos el peso calculado al arreglo de pesos
		weights.append(weight)
		# y lo sumamos a la variable de peso total
		total_weight += weight
```

#### Eligiendo el movimiento a realizar

Es momento de que la IA elija el movimiento que hará con base en los pesos calculados. Para ello usaremos pesos acumulados que funcionarán como uno de los valores que considerará la IA para aleatoriamente decidir qué realizar. Saldremos del `for` pero seguiremos escribiendo en la misma función. Escribamos pues lo siguiente:

```gdscript
	# Variable para el peso acumulado
	var cumulative_weight = 0
	# Variable aleatoria entre 0 y el peso total
	var rand_weight = randi_range(0,total_weight)

	# Para cada peso en el arreglo de pesos:
	for i in len(actions):
		# agregamos el peso actual al acumulado
		cumulative_weight += weights[i]

		# Si el peso random es menor al acumulado:
		if rand_weight < cumulative_weight:
			# devuelve la actual acción del ciclo
			return actions[i]
```

Probemos el combate. Variemos la vida tanto del jugador como de la IA para verificar que el comportamiento de esta es coherente con las diversas situaciones que se puedan presentar en combate.

## Pantalla de fin del juego

Configuremos el fin del juego basados en si el jugador gana o pierde el combate. Esto implica crear una pantalla que aparezca cuando la pelea termine.

### Creando la pantalla

En la escena de batalla, seleccionamos el nodo `CanvasLayer` y le agragamos un `Panel` que llamaremos `EndScreen`. Le aplicamos un anclaje "Completo". Enseguida nos dirigimos a su *Theme Overrides -> Styles* y creamos un nuevo *StyleBoxFlat*, al cual le daremos un color a nuestro gusto. En este caso, le pusimos un color verdoso.

Le añadiremos como hijo un `Label` cuyo nombre será `HeaderText` y cuyo anclaje será "Centro". Escribimos algún mensaje adecuado en el campo de texto (como ejemplo, escribimos "¡Has ganado el combate!"). Luego debemos crear un nuevo recurso `LabelSettings` y lo desplegamos. Cambiamos el tamaño de fuente y alineamos el texto tanto vertical como horizontalmente.

Ahora incluiremos un botón a `EndScreen`. Este se llamará `PlayAgainButton` y lo anclamos en el centro. Posteriormente lo bajamos un poco para que no se estorbe con el texto ya existente y cambiamos el tamaño de fuente a `32`, por ejemplo (esto se hace en *Theme Overrides*). Le ponemos un texto alusivo (en este caso le pusimos "Juega de nuevo").

### Programando la pantalla

Debemos cumplir dos objetivos con este código: presentar la pantalla y recargar la escena cuando el jugador quiera jugar de nuevo.

Unimos un script al `EndScreen` y lo llamamos tal como nos sugiere Godot (`end_screen.gd`). En este declaramos una variable que hace referencia a la etiqueta y creamos la función que estará actualizando el texto en la misma:

```gdscript
# Referencia a la etiqueta
@onready var header_text : Label = $HeaderText

# Actualiza el texto en la etiqueta
func set_header_text(text_to_display : String):
	header_text.text = text_to_display
```

Luego conectamos el `PlayAgainButton` con su respectivo `EndScreen`. Eso lo hacemos seleccionando dicho botón y en *Señales* damos doble clic en `pressed()`. En el cuadro que aparezca debemos asegurarnos de elegir el `EndScreen` y no `Main`. Dentro de la función creada agregamos la línea

```gdscript
	# Recarga la escena actual
	get_tree().reload_current_scene()
```

Esto recargará la escena actual, que viene siendo `battle.tscn`.

Ahora nos dirigimos al `game_manager.gd` para modificarlo y permitir que se detecte quién ha ganado para mostrar la pantalla pertinente.

Primero declaramos una variable:

```gdscript
# Referencia al panel
@onready var end_screen = $CanvasLayer/EndScreen
```

Luego creamos un par de funciones justo antes de `next_turn()`:

```gdscript
# Revisa la salud del jugador
func _on_player_take_damage (health : int):
	# Si la vida llega a 0:
	if health <= 0:
		# termina el juego y vence la IA
		end_game(ia_character)

# Revisa la salud de la IA
func _on_ia_take_damage (health : int):
	# Si la vida llega a 0:
	if health <= 0:
		# termina el juego y gana el jugador
		end_game(player_character)
```

El siguiente paso es conectar esas funciones a las señales `OnTakeDamage` del jugador y de la IA, además de asegurarnos de ocultar la pantalla final por defecto. Nos dirigimos a la función `_ready()` y la dejamos tal como se muestra en el siguiente bloque:

```gdscript
func _ready():
	# Conexión de señal de daño al jugador
	player_character.OnTakeDamage.connect(_on_player_take_damage)
	# Conexión de señal de daño a la IA
	ia_character.OnTakeDamage.connect(_on_ia_take_damage)

	# Ocultamos la pantalla final por defecto
	end_screen.visible = false

	# Siguiente turno
	next_turn()
```

Por último creamos la función `end_game()`, justo antes de `next_turn()`.

```gdscript
# Define quién gana y muestra la pantalla final
func end_game (winner : Character):
	# Vuelve verdadera la variable
	game_over = true
	# Vuelve visible la pantalla final
	end_screen.visible = true
	# Si el jugador gana:
	if winner == player_character:
		# la etiqueta muestra el texto adecuado.
		end_screen.set_header_text("¡Ganaste!")
	# Si no:
	else:
		# la etiqueta muestra el mensaje contrario.
		end_screen.set_header_text("¡Has perdido!")
```

Hemos terminado la parte "técnica" de nuestro mini juego de combate por turnos.

## Retoques visuales

### Diferenciando los caracteres

En este momento ambos caracteres son iguales y con excepción de la ubicación, nada los diferencia. Resolvamos eso. Abrimos `character.gd` y creamos una variable que controlará la dirección a donde volteará el personaje, dependiendo de si es el jugador o la IA.

```gdscript
# Booleana que hace girar a la izquierda
@export var facing_left : bool = false
```

Luego necesitamos referenciar el sprite y modificar sus propiedades con base en la variable recién creada.

```gdscript
# Referencia al sprite del caracter
@onready var sprite : Sprite2D = $Sprite2D
```

Nos dirigimos a la función `_ready()` y agregamos:

```gdscript
func _ready() -> void:
	# Tomamos el valor de la variable lógica correspondiente
	sprite.flip_h = facing_left
```

Entonces seleccionamos el nodo `IACharacter` de la escena `battle.tscn` y activamos su propiedad *Facing Left*. Guardamos y si ejecutamos el juego, este ya debería mostrar los caracteres mirando en direcciones opuestas.

### Cambiando al caracter

Le daremos a la IA otra apariencia. Crearemos una variable más para permitir la carga de otra textura. En el mismo `character.gd` agregamos:

```gdscript
# Variable para cargar diferentes texturas
@export var display_texture : Texture2D
```

Y en `_ready()` incluimos al final la línea:

```gdscript
	sprite.texture = display_texture
```

Ahora agregamos arrastrando desde el sistema de archivos la textura correspondiente hacia la nueva propiedad *Display Texture* del inspector, seleccionando tanto `PlayerCharacter` como `IACharacter` en la escena `battle`.

### Efectos visuales de daño

Daremos un efecto visual al recibir daño. Así que nos vamos a la escena `character` y le agregamos un script al nodo `Sprite2D` y le llamamos `character_visual.gd`.

En este nuevo script crearemos una función llamada `_damage_visual()` que tomará el parámetro entero llamado `health`.

```gdscript
func _damage_visual(health: int):
	# Aplicamos un filtro rojo
	modulate = Color.RED
	# Hacemos que dure 0.05 s
	await get_tree().create_timer(0.05).timeout
	# quitamos el filtro rojo
	modulate = Color.WHITE
```

Dentro de `_ready()` ponemos:

```gdscript
	# Obtenemos el nodo padre
	var character = get_parent()
	# Conectamos a la señal de recibir daño
	character.OnTakeDamage.connect(_damage_visual)
```

Y ahora daremos el efecto de vibración al sprite. Primero agregamos unas cuantas funciones:

```gdscript
# Variable que aplica el desfase
@onready var base_offset: Vector2 = offset
# Intensidad de la sacudida
var shake_intensity: float = 0.0
var shake_damping: float = 10.0
```

Luego creamos la función que generará la sacudida aleatoria:

```gdscript
# Desfase aleatorio para la sacudida del sprite
func _random_offset() -> Vector2:
	var x = randf_range(-shake_intensity, shake_intensity)
	var y = randf_range(-shake_intensity, shake_intensity)
	return Vector2(x, y)
```

Y agregamos lo siguiente a la función `_process()`:

```gdscript
func _process(delta: float) -> void:
	# Si la intensidad es mayor a cero:
	if shake_intensity > 0:
		# Interpola la vibración gradualmente
		shake_intensity = lerpf(shake_intensity, 0, shake_damping * delta)
		# Desfase aleatorio
		offset = base_offset + _random_offset()
```

Por último, en la función `_damage_visual()` agregamos justo después de modular a rojo esta línea de código:

```gdscript
	# Intensidad de sacudida
	shake_intensity = 10.0
```

### Darle vida a los personajes

Toca darle mayor vida a nuestro combate. Hagamos que los personajes "respiren" en el campo de batalla. En el `character_visual.gd` agregamos más variables:

```gdscript
# Intensidad del movimiento
var bob_amount : float = 0.02
# Velocidad del movimiento
var bob_speed : float = 15.0
```

Luego, dentro de `_process()`, antes del `if`, declaramos lo siguiente:

```gdscript
	# Tomamos el tiempo desde el sistema
	var t = Time.get_unix_time_from_system()
	# Usamos la función seno
	var y_scale = 1 + (sin(t * bob_speed) * bob_amount)
	# Escalamos en y basados en el seno
	scale.y = y_scale
```

### Indicar cuál personaje está activo

Ahora crearemos un efecto visual que haga más fácil identificar de quién es el turno. El personaje que se encuentre activo se mostrará de mayor tamaño. En términos cuantitativos, cambiaremos la escala del sprite correspondiente a `1.1` cuando esté activo y a `0.9` en caso contrario.

Nos dirigimos al script `character.gd` y ubicamos las funciones `begin_turn()` y `end_turn()`. Dentro de ellas ya deberíamos tener asentado este cambio en una variable existente que se llama `target_scale`.

Pues bien, editaremos `_process()`:

```gdscript
func _process(delta: float):
	# Escala en X
	scale.x = lerp(scale.x, target_scale, delta * 10)
	# Escala en Y
	scale.y = lerp(scale.y, target_scale, delta * 10)
```

## El sonido

Agreguemos el sonido de fondo al combate. Abriremos la escena `battle.tscn` y seleccionamos el nodo `Main`. Le añadiremos un nodo `AudioStreamPlayer` que renombraremos como `Music`. En su propiedad *Stream* cargaremos el archivo `battle_music.wav`. Cambiamos el volumen a `-15` dB en *Volume dB* y activamos su propiedad *Autoplay* (es lo que nos permite reproducir este audio al iniciar el juego).

Ahora bien, el audio no se escuchará de manera ininterrumpida. Para resolverlo, abrimos el panel *Importar* que está al lado del árbol de escenas. Ahí buscamos la propiedad *Modo Loop* y la cambiamos a `Forward`. Debemos dar clic al botón *Reimportar* para guardar el cambio.

## Moviendo el fondo

Seleccionamos el nodo `Background` de la escena `battle` y en su propiedad *Size X* simplemente multiplicamos el valor actual por 3, dejándolo en `4512`. Luego lo movemos lo más posible hacia la izquierda pero aún cubriendo nuestra escena.

Le agregamos un script que llamaremos `Background.gd` y declaramos las variables:

```gdscript
# velocidad del movimiento
@export var speed : float = 200
# Extensión
@export var extents : float = 1024
# Posición inicial
@onready var start_pos : Vector2 = position
# Cambio de color
@export var color_lerp : Gradient
```

Luego, en `_process()` ponemos lo siguiente

```gdscript
func _process(delta):
	position.x += speed * delta
```

Para crear la ilusión de un escenario infinito, necesitamos reiniciar el fondo a su posición original una vez que alcance cierto punto, el cual será su extensión total. Agregamos al final de `_process()` lo siguiente:

```gdscript
	# Si la posición actual en X menos la original supera la extensión:
	if position.x - start_pos.x >= extents:
		# reiniciamos la posición
		position = start_pos
```

Como toque final, cambiaremos el color del fondo para dar mayor dinamismo. Con `Background` aún seleccionado, vamos al inspector y en la propiedad *Color Lerp* creamos un nuevo gradiente. Damos clic en él para desplegarlo y cambiamos el color de ambos extremos (izquierdo y derecho), además del color del centro de la barra. Lo dejamos a nuestro gusto y criterio. En nuestro caso, dejamos un verde apagado en la izquierda, un naranja en la derecha y un verde brillante en medio.

Agregamos al final de `_process()` pero fuera del `if` las siguientes líneas:

```gdscript
	# Obtenemos el tiempo del sistema
	var time = sin(Time.get_unix_time_from_system())
	time = (time + 1) / 2
	# Aplicamos un filtro de color basados en el tiempo
	modulate = color_lerp.sample(time)
```

## Menú de inicio

Terminaremos nuestro juego con una escena principal en la que elegiremos si jugar o salir del título.

Creamos una escena con un nodo raíz del tipo `Control` que llamaremos `Menu`. Le añadiremos un `TextureRect` que llamaremos `Background` y le cargaremos en mismo fondo que a nuestra escena de batalla. Le aplicamos a ambos nodos un anclaje "Completo" y cambiamos la propiedad *Expand Mode* de `Background` a `Fit Height`.

Seleccionamos `Menu` y añadimos un `Label` que renombramos como `Title`. Cambiamos su texto a "Micro-RPG" y mediante un nuevo recurso *Label Settings* modificamos la fuente a `64` px de tamaño, un color a nuestro gusto y una línea exterior blanca de `25` px. Aplicamos un anclaje de "Centro" y alineamos el texto de igual manera en sentido horizontal y vertical.

Seleccionamos `Menu` de nuevo y agregamos un `Button`. Le ponemos de nombre `PlayButton` y en su texto escribimos "JUGAR". En *Theme Overrides* cambiamos el tamaño de fuente a `40` px. Lo redimensionamos a nuestro criterio y lo anclamos al centro. Luego lo movemos hacia abajo.

Duplicamos el botón y le renombramos `QuitButton`. Enseguida cambiamos su texto a "SALIR".

Terminemos por programar el comportamiento de los botones. Adjuntamos un script a `Menu` y lo guardamos como Godot nos sugiere. Enseguida seleccionamos cada botón para conectar su respectiva señal `pressed()` al mismo script de `Menu`. Para cada función generada agregamos lo siguiente:

```gdscript
func _on_play_button_pressed() -> void:
	get_tree().change_scene_to_file("res://scenes/battle.tscn")

func _on_quit_button_pressed() -> void:
	get_tree().quit()
```

Establecemos `menu.tscn` como la escena principal y guardamos. Hemos terminado nuestro micro-RPG.




















