# Plataformas 2D

## Diseño del juego

Antes de entrar directamente al desarrollo como tal, siempre es buena idea ir aterrizando los objetivos que queremos, las mecánicas de nuestro juego, movimientos permitidos, si habrá o no coleccionables, comportamiento de los enemigos, objetivos que plantearemos al jugador, etc. Es lo que llamamos "Game Design" o Diseño del Juego. Iremos ahondando en los diversos puntos.

### Objetivos

- El jugador debe recolectar monedas y evitar el contacto con los enemigos.
- Su meta es alcanzar el área final en cada nivel, señalada por una bandera.

### Controles y movimientos

El personaje será controlado por teclado y mando, con los siguientes controles principales:

- Movimiento, de izquierda a derecha.
- Salto

Para mejorar la experiencia en el control, agregaremos una aceleración cuando el personaje comience a moverse y frenarle cuando el jugador suelte las teclas de movimiento.

Esas adiciones crearán un movimiento que se sienta más natural y suave.

### Enemigos y sistema de daño

Incluiremos enemigos con movimientos predeterminados entre dos puntos específicos. Definiremos la distancia que recorrerán y el ángulo en que lo harán.

Cuando un enemigo toque al personaje dispararemos el sistema de daño que consistirá de:

- Restarle una vida al jugador.
- Una interfaz de usuario que muestre dicho efecto (usaremos corazones representando cada oportunidad).
- Cuando el caracter sea dañado, agregaremos un breve "flash" rojo y un ligero efecto de temblor a la pantalla.
- Reproduciremos un sonido de daño.

### Coleccionables

Colocaremos monedas a través del escenario como coleccionables. Al recogerlas, el puntaje aumentará por $1$. Le aplicaremos a las monedas efectos para que parezcan estar girando y flotando, además de agregar un efecto de sonido cuando sean recogidas.

### Fin del nivel

Colocaremos una bandera que represente el final del nivel, la cual también fungirá como un "portal" hacia el siguiente escenario.

### Menu del juego

El juego contará con un sencillo menú que permita iniciar el juego o bien, salir de él.

Con todo esto en mente, comencemos con el desarrollo.

## Configurando el proyecto

Primero que todo, crearemos las carpetas típicas: `assets`, `scripts` y `scenes`. También importaremos los "assets" que utilizaremos, tal y como lo hemos venido haciendo, llevándolos a su carpeta correspondiente.

### Configurando el escenario

Para iniciar crearemos una capa de "mapa de baldosas", que es donde pintaremos nuestro mapa de "baldosas". Las baldosas o mosaicos son básicamente elementos organizados en una rejilla que no solo cumplen una función estética (podemos pensar que son el fondo), si no que también son funcionales, ya que pueden representar paredes, pisos o portales y comportarse como tales.

Ya estamos en una escena, así que agregamos un nodo `Node`, le llamamos `Main` y enseguida guardamos la escena como `level_1.tscn`. Después le agregamos un nodo `TileMapLayer` a `Main`. Veremos que en la parte inferior de Godot aparece otro panel. Este es el editor de tilemaps. Nos iremos familiarizando con él en lo sucesivo.

Con `TileMapLayer` seleccionado, buscamos su propiedad *Tile Set* y damos clic en donde pone *vacío*. Ahí clicamos en *Nuevo -> TileSet*. Ahora aparecerá otro panel inferior, el editor de tilesets. Damos clic en su propio botón *+ -> Atlas* y cargamos `assets/Sprites/Tiles/tiles_packed.png`. Confirmamos el mensaje que aparezca.

Antes de continuar, cabe mencionar que es una buena práctica guardar el *tileset* como un elemento independiente de la imagen que lo conforma. Esto puede realizarse desplegando la misma propiedad *Tile Set* y dando clic en *Guardar como*. Deberíamos guardarlo con el nombre que deseemos pero en la misma ubicación que la imagen que le da origen (se guardará como un recurso, con la extensión `.tres`).

Hecho lo anterior, podremos notar que la división en mosaicos de nuestro conjunto no cuadra con el mismo, ya que deja espacios sin abarcar, sobretodo en la orilla derecha y en la inferior. Ese problema lo corregimos cambiando el *Tamaño de región* que está en el editor de tilesets. El valor que tiene es de `16` para *X* y *Y*. Lo aumentamos a `18`. Debemos comprobar que efectivamente ahora queda todo el set incluido y subdividido.

El cambio anterior acarrea otro detalle que debemos corregir, y es que el *Tile Size* en el inspector sigue siendo de `16`. Cambiémoslo a `18` también.

Existe aún otro problema. Tenemos baldosas "vacías" en los lugares que antes estaban mal divididos. Incluso Godot nos lo advierte con un icono justo encima de nuestro conjunto de mosaicos y ahí mismo nos dice qué debemos hacer para corregirlo: clic en los tres puntos y enseguida *Eliminar Tiles fuera de la textura*.

Ahora agregaremos físicas a nuestras baldosas. En el inspector buscamos el apartado *Physics Layer* y damos clic en *Añadir elemento*. Aparecerán dos arreglos, uno de capas de colisón y otro de máscaras. Ahora nos dirigimos al editor de tilesets y seleccionamos la pestaña *Pintar* y desplegamos el botón *Selecciona un editor de propiedades*. Damos clic en *Capa de Física 0*. Ya podemos ir "pintando" con físicas todos los mosaicos que deseamos que funcionen como elementos de colisión en el juego (suelos, paredes, tuberías, etc). Funciona dando clic o arrastrando el mouse. Si llegamos a aplicar esta capa a un mosaico que no queramos, podemos dar clic en los tres puntos y luego en *Limpiar* y ya podremos quitarle la "pintura" de físicas.

### Pintando el escenario

El siguiente paso es "pintar" las baldosas en nuestra escena, propiamente dicho. No olvidemos guardar nuestro tileset. Seleccionamos `TileMapLayer` y debe aparecer tanto una rejilla naranja a su alrededor como el editor de *Tilemaps*, lo que significa que todo va bien. Con este editor abierto, seleccionamos la baldosa deseada y vayamos pintando nuestro escenario con ella, de acuerdo a lo que tengamos en mente. Dicho editor cuenta con herramientas básicas de pintura en su parte superior. Recordemos que las que tienen capa física son las que funcionarán como elementos de colisón.

No olvidemos cambiar el modo de renderizado de texturas para que estas no se vean borrosas. Puede hacerse de manera global yendo a *Proyecto -> Configuración del proyecto -> General -> Renderizado -> Texturas -> Filtro* y cambiarlo a `Nearest`.

Diseñemos nuestro nivel. De entrada, dejar un espaciado de tres baldosas entre cada plataforma funciona bien para los valores por defecto. Pero no nos limitemos, experimentemos con todas las opciones disponibles de formas y figuras. Pero eso sí, para mantener cierta coherencia, tratemos de utilizar solo mosaicos del "mismo" bioma, por así decirlo.

### Agregando un fondo de escenario

Con `Main` seleccionado agregamos un `Sprite2D` y le cambiamos el nombre a `Background`. Lo arrastramos de manera que quede justo debajo de `Main`, para que así sea un elemento de fondo. En su propiedad *Texture* desplegamos y tras seleccionar *Cargar* abrimos `assets/Sprites/Backgrounds/backgroundForest.png`. Lo movemos de manera que su línea de horizonte quede por debajo de nuestras plataformas y que cubra horizontalmente todas ellas de manera sobrada.

### Configurando la escena del personaje

Debido a que nuestro personaje deberá interactuar con las físicas del juego, resulta adecuado utilizar un nodo especialmente hecho para este tipo de escenas. Con `Main` seleccionado, agregamos un `CharacterBody2D` y le renombramos `Player`. También lo convertiremos en una escena por sí mismo, así que lo seleccionamos y le damos clic derecho, escogemos *Guardar rama como escena* y lo dejamos como `player.tscn`. Le damos clic a este último para abrirlo como una pestaña más. Con `Player` seleccionado agregamos un nodo `Sprite2D` y en su *Texture* cargamos `assets/Sprites/Characters/character_0000.png` y le cambiamos su nombre a `PlayerSprite`.

Debemos cambiar el origen del nodo `SpritePlayer`, debido a que deseamos que la referencia a él sean sus pies. Modificamos su *Offset Y* a un valor que nos permita centrarlo en sus pies, `-12` lo logra. Podemos corroborarlo si vemos la posición del caracter en la escena `main.tscn`. No se recomienda transformar la posición de los nodos raíz visualmente, ya que ello debería realizarse mediante código.

Acto seguido, agregamos a `Player` su respectiva forma de colisión. Una que funciona bien para nuestro personaje es la *CapsuleShape2D*. Esta sí podemos moverla de manera que cubra bien al jugador, funciona bien cambiar su *Position Y* a `-12`. Ajustamos la forma al personaje para que nos parezca adecuada y guardamos la escena.

### Creando la cámara

El siguiente paso es establecer `level_1.tscn` como la escena principal si es que no lo habíamos hecho. Enseguida, podemos probar el juego. Notaremos que se ve mal, y eso se debe a que Godot muestra en pantalla la que hemos dejado por defecto. Es momento de trabajar con una cámara que siga al caracter.

Agregaremos a `Player` un nodo `Camera2D` en su respectiva escena y veremos que aparece otro rectángulo encerrando a nuestro personaje. Es su cámara personal. Lo comprobaremos si corremos el juego. Pero aún así se sigue viendo raro, y es porque faltan unas cuantas configuraciones. Seleccionamos `Camera2D` y cambiamos su propiedad *Zoom* a `3` y *transform -> Position Y* a `-24`. Solo resta agregarle a nuestro `Player` un par de nodos más: un `AnimationPlayer` y un `AudioStreamPlayer`.

### Mapeando los controles

Es el proceso típico. Nos vamos a *Proyecto -> Configuración del proyecto* y pestaña *Mapa de entrada*. Asignamos las tres acciones a las teclas que consideremos pertinentes (típicamente las direccionales para el movimiento y {{<kbd Space>}} para el salto). Igual podemos agregar el mando y teclas adicionales.

## Programando al jugador

### Moviendo al jugador

Abrimos la escena `player` y seleccionamos `Player`. Le adjuntaremos un script vacío en el cual declaramos las siguientes variables:

```gdscript
# velocidad máxima a la que nos moveremos
@export var move_speed : float = 100
# tasa de aceleración del personaje
@export var acceleration : float = 50
# tasa a la que iremos frenando al dejar de presionar algún control
@export var braking : float = 20
# fuerza de la gravedad aplicada al jugador
@export var gravity : float = 500
# fuerza del impulso al saltar
@export var jump_force : float = 200

# variable donde almacenaremos las entradas para el movimiento
var move_input : float
```

Ahora, para implementar el movimiento, agregaremos lo siguiente

```gdscript
func _physics_process(delta: float):
	# obtener la entrada
	move_input = Input.get_axis("left", "right")
	# movimiento
	velocity.x = move_input * move_speed
	move_and_slide()
```

Lo hacemos de esta manera para permitir que el motor esté aplicando la misma consistencia en cuanto a tiempo, sin importar la tasa de cuadros por segundo.

La función `Input.get_axis("left", "right")` devuelve un valor de `-1` si se presiona la entrada izquierda y `1` si es la derecha (será `0` si no presiona algo). Por otro lado, `velocity.x = move_input * move_speed` determina la velocidad horizontal del jugador, de acuerdo con la entrada y la velocidad de movimiento. Por último, recordemos que `move_and_slide()` aplica la velocidad a la posición del personaje y maneja la detección de colisiones.

### Agregando gravedad

Modificaremos el componente vertical del vector velocidad del personaje. Agregaremos gravedad al caracter solo cuando este se encuentre en el aire. Escribamos una condicional que estará verificando si el jugador está o no tocando el piso, y si así es, agregaremos el producto de `gravity` por `delta` al componente vertical del vector del jugador. Eso lo ponemos justo al inicio de `_physics_process(delta)`:

```gdscript
    # Gravedad
    if not is_on_floor():
        velocity.y += gravity * delta
```

Ahora el personaje debería caer y no flotar.

### Agregando el salto

El personaje debe poder saltar solo si se cumplen tres condiciones: que el jugador haya presionado la tecla de salto, que esté en el suelo y que la velocidad se modifique antes de llamar la función `move_and_slide()`.

Debido a que estaremos leyendo el estado del jugador todo el tiempo, agregamos el código correspondiente a la función `_physics_process()`, antes precisamente de que se invoque al `move_and_slide()`:

```gdscript
# Salto
# Si la tecla de salto ha sido presionada y estamos en el suelo...
if Input.is_action_pressed("jump") and is_on_floor():
	# entonces...
	velocity.y = -jump_force
```

Después de implementar el salto, toca suavizarlo para que la animación se vea más natural. Para ello utilizaremos la función `lerp()`, la cual permite suavizar las transiciones entre dos puntos, mejorando las animaciones al hacerlas más fluidas.

Tras especificar un valor de inicio, un valor de fin y un peso, `lerp()` calculará un nuevo valor que es un porcentaje del camino entre el valor inicial y final (es decir, interpolará valores), creando un movimiento suave y continuo.

En la misma función en la que estamos, cambiaremos la línea del movimiento `velocity.x` por la interpolación.

```gdscript
if move_input != 0:
		# entonces la velocidad en x es interpolada entre el reposo y la aceleración
		velocity.x = lerp(velocity.x, move_input * move_speed, acceleration * delta)
	# si no
	else:
		# velocidad en x es interpolada entre el movimiento y el "freno"
		velocity.x = lerp(velocity.x, 0.0, braking * delta)
```

### "Girando" el *sprite*

Si hemos probado el juego, debimos notar que el personaje no mira en la dirección en la que se mueve. Corrijamos eso. Primero, crearemos una variable que haga referencia al nodo `PlayerSprite`, pero desde que dicho nodo esté listo. Nos vamos al principio de `player.gd` y escribimos justo después del `extends CharacterBody2D`

```gdscript
@onready var sprite : Sprite2D = $PlayerSprite
```

Enseguida crearemos la función `_process(delta)` y ahí agregaremos el "giro" del sprite. Lo hacemos en esta función debido a que queremos que esté revisando continuamente el estado del jugador pero sin físicas (lo de las físicas ya lo hace `_physics_process(delta)`).

```gdscript
func _process(delta: float):
	# Si el caracter se está moviendo:
	if velocity.x != 0:
		# entonces si la velocidad en x es positiva, se gira el sprite
		sprite.flip_h = velocity.x > 0
```

::: {.callout-note}

## Nota

Para que no surjan errores, en este caso en específico tenemos que activar la propiedad *Flip_h* del `Sprite2D`, ya que está volteando a la izquierda por defecto.
:::

### Animando al jugador

#### Estado inactivo

Agregaremos un `AnimationPlayer` al nodo `Player` en su respectiva escena. Creamos una nueva animación y le llamamos *idle*. Cambiaremos la duración de la animación a `0.5`, ademas de habilitar la *reproducción automática al cargar*. Fijamos el editor de animaciones y seleccionamos el `SpritePlayer`. Nos vamos al inspector y en la propiedad *Texture* damos clic en la llave a la izquierda. Creamos una pista *RESET* y dejamos todo como está. Las animaciones con pistas RESET son aquellas que regresan a su estado original cuando termina la animación en sí.

#### Animación de movimiento

En el editor de animaciones creamos otra a la que llamamos *move*. De la misma manera seleccionamos enseguida el `SpritePlayer`, luego arrastramos el archivo `assets/sprite/character/character_0001.png` a su propiedad *Texture* y creamos una clave de animación (pista RESET también). En el editor ajustamos la duración de la animación a `0.25` y activamos su animación en bucle. Enseguida movemos el cursor al segundo `0.125` y arrastramos el archivo `png` original (`character_0000.png`). Creamos otra clave y probamos la animación.

#### Animando el salto

Mismo procedimiento que *idle*, con la excepción de que utilizaremos únicamente el `character_0001.png`, con bucle y duración de `0.5`.

### Programando las animaciones del jugador

En `player.gd` agregaremos una nueva función que llamamos `_manage_animations()`. En ella controlaremos las animaciones.

```gdscript
func _manage_animations():
	# si el caracter está en el aire:
	if not is_on_floor():
		# reproduce "idle"
		$AnimationPlayer.play("jump")
	# pero si se está moviendo:
	elif move_input != 0:
		$AnimationPlayer.play("move")
	# y si nada de eso ocurre:
	else:
		$AnimationPlayer.play("idle")
```

Finalmente, en `_process(delta)` mandamos llamar nuestra nueva función hasta lo último, fuera del `if`:

```gdscript
_manage_animations()
```

## Programando a los enemigos

Crearemos unos cuantos enemigos que seguirán rutas predefinidas al moverse, en un patrón de ida y vuelta entre dos puntos específicos. Los enemigos harán daño al jugador cuando lo toquen, por lo que su objetivo será evitarlos.

### Creando al enemigo

Para los enemigos utilizaremos un nodo `Area2D`, ya que este no colisiona físicamente con otros nodos, pero sí detecta cuando es tocado por estos. En la escena `level_1.tscn` agregaremos pues un nodo de dicho tipo a `Main`, para renombrarlo como `Enemy`. Luego le agregamos su respectivo `Sprite2D` (lo renombramos como `EnemySprite`), cuya propiedad `Texture` será ocupada por la carga del archivo `character_0024.png`, el cual es un murciélago.

Sigue agregarle a `Enemy` su nodo y respectiva forma de colisión. Será una *CircleShape2D*. Démosle un tamaño más pequeño que el sprite en sí, para ayudar un poco a que el jugador pueda esquivarle.

Debido a que animaremos al enemigo, le agregaremos un nodo `AnimationPlayer`.

Adjuntemos un script a `Enemy`, llamándole `enemy.gd`. Declararemos cuatro variables de entrada:

```gdscript
# dirección del movimiento
@export var move_direction : Vector2
# velocidad del movimiento
@export var move_speed : float = 20

# variable lista cuando el nodo esté listo, posición inicial
@onready var start_pos : Vector2 = global_position
# posición final
@onready var target_pos : Vector2 = global_position + move_direction
```

Una vez que el enemigo haya alcanzado su posición final, debemos hacer que lo sepa y ahora se mueva de nuevo hacia la original, en un ciclo de ida y vuelta.

::: {.callout-note}

## Importante

La variable `global_position` se refiere a la posición del nodo en el viewport, propiedad que podemos ver en el inspector como *Position.x* y *Position.y*.
:::

Agregamos las siguientes líneas al script actual:

```gdscript
func _physics_process(delta):
	# Se mueve hacia delante, a la posición objetivo a la velocidad indicada
	global_position = global_position.move_toward(target_pos, move_speed * delta)
	# si la posición global es igual a la objetivo:
	if global_position == target_pos:
		# si la posición objetivo y la inicial son la misma:
		if target_pos == start_pos:
			# el objetivo es la posición inicial mas la dirección del movimiento
			target_pos = start_pos + move_direction
		# si no:
		else:
			# la posición objetivo y la inicial son la misma
			target_pos = start_pos
```

#### Probando el movimiento del enemigo

Habilitemos el viewport 2D y llevemos al nodo del enemigo a la posición que deseamos que ocupe. Enseguida editaremos la variable `move_direction` a valores de `(0, -50)`. Ejecutemos el juego y confirmemos que todo funcione bien.

#### Conectando señales

Ahora iremos a la escena `player` y seleccionaremos `Player`. Crearemos un grupo al que llamaremos *Players* y enseguida seleccionamos `Enemy` en su propia escena y conectamos su señal `body_entered()` al mismo nodo `Enemy`. En la función que aparecerá escribimos lo siguiente:

```gdscript
# algo entró al Area2D
func _on_body_entered(body: Node2D):
	# Si el cuerpo que entró no está en "Players":
	if not body.is_in_group("Players"):
		# regresa y hace nada
		return
	# si no, imprime "Daño"
	print("Daño")
```

Ejecutemos el juego y confirmemos que el daño sí se "marca" en el *output* de Godot.

#### Animando al enemigo

Escojamos el nodo `AnimationPlayer` del enemigo en la escena `level_1.tscn`. Debe aparecer el editor de animaciones. Creamos una nueva y le llamamos *fly*. Luego seleccionamos el `EnemySprite` y en su propiedad *Texture* (donde ya debería estar el murciélago) clicamos a su llave para crear una clave con su correspondiente pista RESET. Cambiaremos su duración a `0.4`s. Movemos el cursor de tiempo a `0.18`s y arrastramos el `characters/character_0025.png` (murciélago con las alas arriba) al *Texture* del `EnemySprite` y clicamos en la llave. Ya tenemos dos fotogramas clave. Vamos por un tercero. Llevamos el tiempo al segundo `0.3` y ahora arrastraremos el `character_0026` (murciélago con las alas abajo) al *Texture*, creando una nueva clave. No olvidemos activar el *loop de animación*.

Para habilitar la animación agregamos lo siguiente justo después de la declaración de las variables:

```gdscript
func _ready():
	# reproduce "fly" justo al aparecer en escena
	$AnimationPlayer.play("fly")
```

## El sistema de daño

Los enemigos nos dañarán si nos tocan. Cada vez que eso suceda perderemos un punto de vida. Tendremos tres al inicio, llegando a cero, el juego se tendrá que reiniciar.

### Configurando la barra de vida

Primero crearemos una variable en la que guardaremos los puntos de vida del caracter (en `player.gd`):

```gdscript
# puntos de vida
@export var health : int = 3
```

### Programando el sistema de daño

Luego creamos la función que será ejecutada cuando recibamos daño y verificará si la vida ha perdido todos sus puntos:

```gdscript
func take_damage(amount : int):
	# perdemos una cantidad de vida
	health -= amount
	# si la vida llega a cero:
	if health <= 0:
		# perdemos (pero diferimos la llamada a función)
		call_deferred("game_over")
```

Justo debajo de esta función agregaremos la de `game_over()`, en la que recargaremos el primer nivel.

```gdscript
func game_over():
	# volvemos al principio del nivel 1
	get_tree().change_scene_to_file("res://scenes/level_1.tscn")
```

Debemos ahora agregar el disparador de estas funciones. Se encontrará en `enemy.gd`, donde reemplazaremos esto:

```gdscript
# si no, imprime "Daño"
	print("Daño")
```

por esto:

```gdscript
# pero si sí, recibe daño el cuerpo que haya entrado
body.take_damage(1)
```

### Duplicando los enemigos

Guardemos `Enemy` como una escena, seleccionándolo y mediante clic derecho, escogemos *Guardar rama como escena* y lo dejamos como `enemy.tscn`. Ya es posible duplicarlo y colocar sus copias alrededor del escenario. Pongamos las que consideremos necesarias, modificando su velocidad y posición. Agreguemos variedad. Podemos agregar a `Main` un `Node` y arrastrar todos los nodos `Enemy` dentro de él. Por conveniencia, le renombramos `Enemies`.

## Las monedas

### Configurando las monedas

Comenzaremos creando una escena a la que agregaremos un nodo `Area2D` y que llamaremos `Coin`. La escena la guardamos como `coin.tscn`, naturalmente. Le añadiremos un `Sprite2D` que renombramos como `CoinSprite` y cargamos en su *Texture* el archivo `assets/Sprites/Objects/tile_0151.png` (es la única moneda). Le agregamos a `Coin` su correspondiente `CollisionShape2D` en forma de círculo y la ajustamos al sprite de la moneda.

### Animando las monedas

Adjuntaremos un script a `Coin` y lo dejamos como `coin.gd`. Declararemos las variables iniciales:

```gdscript
# velocidad de rotación
var rotate_speed : float = 3.0
# altura que flota
var bob_height : float = 5.0
# velocidad a la que flota
var bob_speed : float = 5.0

# posición inicial
@onready var start_pos : Vector2 = global_position
# sprite a cargar
@onready var sprite : Sprite2D = $CoinSprite
```

Usaremos la función `_physics_process()` ya que requerimos físicas y ondas sinusoidales para el movimiento y rotación de las monedas:

```gdscript
func _physics_process(delta):
	# obtener tiempo del SO
	var time = Time.get_unix_time_from_system()
	# rota
	sprite.scale.x = sin(time * rotate_speed)
	# flota arriba y abajo
	var y_pos = ((1 + sin(time * bob_speed)) / 2) * bob_height
	# nueva posición
	global_position.y = start_pos.y - y_pos
```

Hecho esto, instanciamos la escena `coin` a `level_1.tscn`.

### Programando las monedas

Seleccionamos `Coin` y conectamos su señal `body_entered()` al propio nodo `Coin`. En la función que aparece escribimos:

```gdscript
func _on_body_entered(body: Node2D) -> void:
	# Si el cuerpo que entra no está en "Players":
	if not body.is_in_group("Players"):
		# devuelve nada
		return
	# si sí está, llama a la función y mándale un 1
	body.increase_score(1)
	# borra la moneda
	queue_free()
```

En el bloque de código anterior hemos referenciado una función que no existe. Vamos a agregarla en `player.gd`

```gdscript
func increase_score(amount: int):
	print("Punto")
```

Probemos que cuando el jugador toque la moneda, aparece el mensaje "Punto".

Si todo va bien, ya podemos duplicar las monedas alrededor del nivel a nuestro gusto y, si también lo deseamos, agruparlas todas en un nodo `Node`.

## El puntaje

A diferencia de los puntos de vida, en el caso del puntaje deseamos que sea persistente, es decir, que su valor se conserve aunque cambiemos de nivel. Por lo tanto, debemos asegurarnos de programarlo en un script que se autocargue y que se encuentre por encima de todas las escenas.

### Creando el script de autocarga

Vamos a la *Configuración del proyecto* y buscamos la pestaña *Globales*. En la caja que pide el *Nombre del nodo* escribimos `PlayerStats` y damos clic en *Añadir*. Guardamos nuestro script en la carpeta adecuada como `player_stats.gd`. Abrimos dicho script.

Crearemos la variable que guardará el puntaje:

```gdscript
var score : int = 0
```

Nos vamos a `player.gd` y actualizamos la función `increase_score()` para que muestre el puntaje alcanzado.

```gdscript
func increase_score(amount : int):
	PlayerStats.score += amount
	print(PlayerStats.score)
```

Probemos que el puntaje sea persistente.

## Fin del nivel

### Creando la bandera

El final del nivel debe estar en la última plataforma, así que si dejamos una moneda o enemigo en esa área, quizá deseamos quitarla. Luego, seleccionando `Main` en `level_1.tscn`, agregamos otra `Area2D` que llamaremos `EndFlag`. Le añadimos a este nodo un `Sprite2D` (`FlagSprite`) y le llevamos a su *Texture* el archivo `assets/Sprites/Objects/tile_0112.png`. Le añadimos a `EndFlag` su `CollisionShape2D` con forma de círculo y la redimensionamos acorde al sprite.

### Programando la bandera

Le adjuntaremos ya su respectivo script a `EndFlag`. Lo guardamos como `end_flag.gd` y conectamos su señal `body_entered()` a sí mismo. Antes de llenar la función que genera la conexión a señal, en el script declararemos la variable que guardará cuál nivel o escena cargaremos cuandos se alcance la bandera.

```gdscript
# escena que cargará al tocar la bandera
@export var scene_to_load : PackedScene
```

Ya podemos definir la función de la señal:

```gdscript
func _on_body_entered(body: Node2D) -> void:
	if not body.is_in_group("Players"):
		return
	call_deferred("_load_new_scene")

func _load_new_scene ():
	get_tree().change_scene_to_packed(scene_to_load)
```

No podemos (ni deberíamos) poner la misma escena en esta línea, ya que eso podría causar comportamientos extraños, así que llevemos `player.tscn` a la propiedad *Scene to Load* de `EndFlag`. Confirmado que funciona, ya podemos reubicar la bandera a donde queramos. Listo, hemos finalizado la estructura principal del juego.

## Interfaz de Usuario

Nuestra *UI* consistirá de solo dos elementos: la barra de vida representada por corazones y una etiqueta de texto que muestra el puntaje alcanzado.

### Configurando la barra de vida

Nos centramos de momento en la escena `player`. Seleccionando su nodo principal, agregamos un nodo `CanvasLayer`. Este nodo es útil ya que "dibuja" sus elementos de manera independiente, por lo que resulta excelente para los HUDs o la UI.

Con `CanvasLayer` seleccionado, agregamos un nodo `TextureRect`, cuya *Texture* será el asset `tile_0044.png` (precisamente el corazón). Cambiaremos su tamaño, en *Layout -> Transform -> Size* lo dejamos en `80` por `80`. También editaremos su propiedad *Expand Mode* para dejarlo como `Fit Width`.

Volvemos a seleccionar el `CanvasLayer` y añadimos otro nodo, un `HBoxContainer` (lo renombraremos como `HealthContainer`) y le cambiamos su *Size Y* a `80` para que se ajuste bien al corazón del `TextureRect`. Duplicamos este último para contar con los tres corazones por defecto y tras seleccionar los tres, los arrastramos dentro del contenedor. Así deberían quedar bien alineados proporcionalmente.

### Configurando la etiqueta del puntaje

Crearemos un nodo `Label` como hijo de `CanvasLayer` y le llamamos `ScoreText`. En su caja de texto escribimos "Puntaje: 500", solo como un *placeholder*. En la propiedad *Label Settings* agregamos una nueva dando clic en *vacío* y editamos su tamaño a `38`px. Luego, en *Shadow* agregamos una sombra editando el valor de *Alpha* aproximadamente a `135` y aumentamos su tamaño a `6`px. Movemos esta etiqueta un poco para evitar que se traslape con la barra de vida.

Guardamos y ejecutamos el juego. Comprobemos que el `CanvasLayer` sea visible y permanezca en la esquina superior izquierda de la pantalla. Si no es así, deshabilitemos su propiedad *Follow Viewport*. Debemos tener en cuenta que el `CanvasLayer` se dibuja en el viewport del juego, no necesariamente en la cámara.

### Programando la UI

En `player.gd` primero declararemos un par de señales que nos permitan actualizar tanto la vida como el puntaje solo cuando haya cambios en sus valores y no en cada frame. Esto lo hacemos para mantener un rendimiento adecuado. Escribimos al principio de dicho script lo siguiente:

```gdscript
# Actualizar la vida - señal de daño
signal OnUpdateHealth (health : int)
# Actualizar el puntaje - señal de moneda
signal OnUpdateScore (score : int)
```

Enseguida nos vamos a la función `take_damage()` y antes del `if` agregamos:

```gdscript
# emitimos la señal de daño
OnUpdateHealth.emit(health)
```

Luego, dentro de `increase_score()` y en lugar del `print()`

```gdscript
# emitimos señal de incremento de puntaje
OnUpdateScore.emit(PlayerStats.score)
```

Seleccionamos el `CanvasLayer` y le adjuntamos un script. Le guardamos con el nombre por defecto y al principio declararemos las siguientes variables:

```gdscript
# contenedor de corazones
@onready var health_container = $HealthContainer
# los corazones en sí
var hearts : Array = []
# etiqueta del puntaje
@onready var score_text : Label = $ScoreText
# referencia al jugador
@onready var player = get_parent()
```

Crearemos dos funciones que nos permitan actualizar el número de corazones de acuerdo a la vida restante y el puntaje de acuerdo con las monedas recolectadas.

```gdscript
# actualizar el número de corazones
func _update_hearts(health : int):
	pass

# actualizar el puntaje
func _update_score(score : int):
	pass
```

Completamos la función `_ready()`, asignando el arreglo de corazones al contenedor de los mismos. Conectamos las señaeles y actualizamos los valores de vida y puntos.

```gdscript
func _ready():
	hearts = health_container.get_children()
	player.OnUpdateHealth.connect(_update_hearts)
	player.OnUpdateScore.connect(_update_score)
	_update_hearts(player.health)
	_update_score(PlayerStats.score)
```

Ahora sí completamos las funciones que dejamos pendientes. Haremos un barrido por el número de corazones actuales y determinaremos cuántos iconos de corazones mostrar.

```gdscript
# actualizar el número de corazones
func _update_hearts(health : int):
	for i in range(len(hearts)):
		hearts[i].visible = i < health
```
Luego, convertimos el número de puntos a texto y lo mandamos al campo de texto de la etiqueta correspondiente.

```gdscript
# actualizar el puntaje
func _update_score(score : int):
	score_text.text = "Score: " + str(score)
```

Probemos que la UI ya actualice vida y puntos en pantalla.

## Retoques

### Un daño más "visible"

#### Coloreando al caracter

Agreguemos un efecto de daño para cuando un enemigo nos toque. Creamos una función llamada `_damage_flash()` en `player.gd`. Esta función pintará de rojo a nuestro caracter por un tiempo que definiremos nosotros. La agregamos al final del script.

```gdscript
func _damage_flash():
	# coloreamos de rojo
	sprite.modulate = Color.RED
	# creamos un timer que dure 0.5s
	await get_tree().create_timer(0.05).timeout
	# devolvemos el color base
	sprite.modulate = Color.WHITE
```

Para que se muestre este efecto, nos vamos a la función `take_damage()` y agregamos antes del `if`

```gdscript
_damage_flash()
```

#### Vibrando la cámara

Esto se consigue mediante un script que agregaremos a nuestro nodo `Camera2D` de la escena `player`. Le llamaremos `camera_shake.gd`. Comenzamos declarando una variable y luego las funciones correspondientes:

```gdscript
extends Camera2D

# intensidad de la sacudida
var intensity : float = 0

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	# nos conectamos con la señal de daño
	get_parent().OnUpdateHealth.connect(_damage_shake)

func _damage_shake(health : int):
	intensity = 3

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float):
	# disminuiremos la intensidad del daño conforme pase el tiempo
	if intensity > 0:
		# interpolamos decrecientemente
		intensity = lerpf(intensity, 0, delta * 10)
		# el offset de la cámara toma un valor aleatorio
		offset = _get_random_offset()

# función que crea y devuelve el valor de offset para la cámara
func _get_random_offset() -> Vector2:
	var x = randf_range(-intensity, intensity)
	var y = randf_range(-intensity, intensity)
	return Vector2(x, y)
```

### Evitando la caída infinita

Durante las pruebas, es muy seguro que hayamos visto que al caer, no ocurre nada más. Evitemos eso detonando el *game over*. En `player.gd` agregamos al final en `_process()` la línea:

```gdscript
if global_position.y > 200:
    game_over()
```

### Paralaje

Seleccionemos el sprite que contiene el fondo en `level_1.tscn` y modifiquemos su *Scale* a `0.5` y su *Position* a `0, 0`. Añadamos a `Main` un `Node2D` y llamémosle `Backgrounds`, arrastremos ahí el nodo `Background`. Debemos asegurarnos de llevar `Backgrounds` justo debajo de `Main` en el árbol de nodos. Dupliquemos el `Background` unas tres veces y movamos horizontalmente las copias de manera que cubran todo el nivel. Podemos usar un *Position X* de `-512` para la primera copia, `512` para la segunda, y `512+512` para la tercera.

Enseguida adjuntamos un script a `Background` y le dejamos el nombre por defecto. Dentro de este dejamos el código como se muestra:

```gdscript
extends Node2D

# tasa de movimiento relativo al jugador (70% de su velocidad)
var parallax : float = 0.7
# referencia al nodo Player
@onready var player = $"../Player"

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float):
	# Obtenemos la posición global del nodo tras multiplicar la del jugador
	# por parallax
	global_position = player.global_position * parallax
```

Por último, con `Backgrounds` aún seleccionado, nos vamos a su propiedad *Visibility -> Modulate* y la cambiamos a un tono "verdoso" que haga mejor juego con un nivel boscoso.

### El audio

Abrimos `player.gd` y agregamos al principio la referencia al `AudioStreamPlayer` que ya tenemos.

```gdscript
# Referencia al AudioStreamPlayer
@onready var audio : AudioStreamPlayer = $AudioStreamPlayer
```

Luego agregamos las variables que precargarán los efectos de sonido, antes de que sean necesarios.

```gdscript
# precarga del audio de daño
var take_damage_sfx : AudioStream = preload("res://assets/Audio/take_damage.wav")
# precarga del audio de las monedas
var coin_sfx : AudioStream = preload("res://assets/Audio/coin.wav")
```

Crearemos la función que reproduzca los sonidos, de acuerdo lo necesario.

```gdscript
func play_sound(sound : AudioStream):
	# "audio" transmitirá lo que tengamos en "sound"
	audio.stream = sound
	# y lo reproducirá
	audio.play()
```

Luego haremos la llamada a la función con su sonido correspondiente en cada función donde se necesite. Por ejemplo, agregamos a `take_damage()`, antes del `if`:

```gdscript
# reproducimos el sonido de daño
play_sound(take_damage_sfx)
```

Y en `increase_score()`, al final:

```gdscript
# reproducimos el sonido de moneda
play_sound(coin_sfx)
```
Probemos que todos los sonidos se reproduzcan correctamente.

## Añadiendo nuevos niveles

La manera más sencilla de hacerlo es simplemente duplicando el nivel que ya tenemos y modificando sus nodos. En el sistema de archivos damos clic derecho a `level_1.tscn` y le damos en *Duplicar*. Le nombramos `level_2.tscn` y guardamos.

### Cambiando el fondo

Le seleccionamos y lo primero que haremos será cambiar el fondo. Con cada nodo `Background` seleccionado cambiamos su *Texture* por el archivo `assets/Sprites/Backgrounds/backgroundDesert.png`. Al terminar, seleccionamos `Backgrounds` y alteramos su propiedad *Modulate* para dejarle un tono amarillento, más acorde a un desierto.

### Editando el escenario

Seleccionamos `TileMapLayer` y con ayuda del borrador y la herramienta del rectángulo en el editor de tilemaps borramos el mapa de baldosas. Esto con el fin de construir uno nuevo.

Dejamos el diseño de este nuevo nivel al criterio personal. Debemos editar también la posición de enemigos y coleccionables, además de ubicar la bandera final en un punto que consideremos divertido. Cuidemos que el reto sea considerable pero no demasiado frustrante. El juego debe continuar siendo justo.

### Editando la bandera del primer nivel

Una vez que hayamos terminado con el segundo nivel, toca volver al primero. Abrimos `level_1.tscn` y en `EndFlag` cambiamos su propiedad *Scene to Load* desplegándola y dando en *Cargar* la escena `level_2.tscn`. Comprobemos que al tocar la bandera del primer nivel nos lleva al segundo y que el puntaje se haya conservado en la transición.

## Agregando un menú

Crearemos una pantalla de inicio en la que incluiremos un botón de "Play" y otro de "Quit" para comenzar a jugar y quitar el juego, respectivamente.

### Configurando la pantalla de menú

Creamos una nueva escena a la que agregamos como nodo raíz un nodo `Control` que llamamos `Menu`. Guardamos la escena como `menu.tscn`. Agregamos un nodo `TextureRect` al cual cargaremos como *Texture* el fondo del bosque (el mismo del primer nivel) y le aplicamos un anclaje completo. En su propiedad *Expand Mode* le cambiamos a `Fit Height` y lo renombramos como `Background`.

Añadimos a `Menu` un nodo `Label` que llamaremos `Title` y en su campo de texto escribimos el título del juego (le dejamos "Plataformas 2D"). Cambiamos sus propiedades *Horizontal Alignment* y *Vertical Alignment* a `Center` y asignamos un anclaje "Centro". La etiqueta está lista en cuanto a posición pero casi no se ve. Crearemos un nuevo *Label Settings* y lo abrimos dando clic en su icono. Cambiamos el tamaño de fuente a `48`px, el color lo dejamos en un amarillo ligero, ponemos una línea exterior verde de `5`px y una sombra también de `5`px (el *Alpha* se dejó de `112`).

Agregaremos un `Button` a `Menu`. Le llamamos `PlayButton` y escribimos en su propiedad *Text* la palabra "Play". Le ponemos un anclaje de "Centro" y lo redimensionamos como deseemos. Hay que posicionarlo de manera que no se traslape con la pantalla de título.

Duplicamos el `PlayButton` y le llamamos `QuitButton`. Escribimos en su *Text* "Quit" y lo movemos abajo del primer botón.

### Programando la pantalla de menú

Seleccionamos `Menu` y le adjuntamos un script `menu.gd`. Luego seleccionamos el `PlayButton` y conectamos su señal `pressed()` al propio `Menu`. En la función que aparece escribimos

```gdscript
func _on_play_button_pressed():
	# Mandamos a cero el puntaje
	PlayerStats.score = 0
	# cargamos el primer nivel
	get_tree().change_scene_to_file("res://scenes/level_1.tscn")
```

Luego repetimos para el `QuitButton` y escribimos en su señal:

```gdscript
func _on_quit_button_pressed():
	# cerramos el juego
	get_tree().quit()
```

Probemos que los botones funciones. Si todo está bien, toca realizar unos ajustes mínimos. Establecemos `menu.tscn` como la escena principal. Luego, a la bandera de final del segundo nivel le asignamos en *Scene to Load* nuestra nueva escena principal (`menu.tscn`, naturalmente). Y por último, editamos la función `game_over()` de `player.gd` para que cargue la pantalla de menú:

```gdscript
func game_over():
	# volvemos a la escena principal
	get_tree().change_scene_to_file("res://scenes/menu.tscn")
```

Listo, ya hemos terminado nuestro juego de plataformas en dos dimensiones. Ahora solo queda agregar más niveles reutilizando la estructura básica que ya tenemos.







